/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMagicPlates,
  IMagicPlatesInterface,
} from "../../../../../contracts/diamond/facets/MagicPlates/IMagicPlates";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint8[][]",
        name: "plate",
        type: "uint8[][]",
      },
      {
        internalType: "uint256[]",
        name: "delays",
        type: "uint256[]",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMagicPlates__factory {
  static readonly abi = _abi;
  static createInterface(): IMagicPlatesInterface {
    return new Interface(_abi) as IMagicPlatesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMagicPlates {
    return new Contract(address, _abi, runner) as unknown as IMagicPlates;
  }
}
