/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMagicPlates__factory } from "./IMagicPlates__factory";
export { NFTFacet__factory } from "./NFTFacet__factory";
export { PltsCore__factory } from "./PltsCore__factory";
