/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuctionHouseInit } from "./AuctionHouseInit";
export type { DiamondInit } from "./DiamondInit";
export type { MagicPixelsInit } from "./MagicPixelsInit";
export type { MagicPlatesInit } from "./MagicPlatesInit";
