/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  AuctionHouseInit,
  AuctionHouseInitInterface,
} from "../../../../contracts/diamond/upgradeInitializers/AuctionHouseInit";

const _abi = [
  {
    inputs: [],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50606580601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063e1c7392a14602d575b600080fd5b00fea2646970667358221220a6fd6117bfbd29d85f6338cf9f5fbcd5412796f47b8b6dfedc1dc421121cc5a964736f6c63430008120033";

type AuctionHouseInitConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AuctionHouseInitConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AuctionHouseInit__factory extends ContractFactory {
  constructor(...args: AuctionHouseInitConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AuctionHouseInit & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AuctionHouseInit__factory {
    return super.connect(runner) as AuctionHouseInit__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AuctionHouseInitInterface {
    return new Interface(_abi) as AuctionHouseInitInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AuctionHouseInit {
    return new Contract(address, _abi, runner) as unknown as AuctionHouseInit;
  }
}
