/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MagicPixelsInit,
  MagicPixelsInitInterface,
} from "../../../../contracts/diamond/upgradeInitializers/MagicPixelsInit";

const _abi = [
  {
    inputs: [],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610220806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063e1c7392a14610030575b600080fd5b61003861003a565b005b7fa32ac351050f01911d543184484dd0b56f1a44a545355195dea6fa48038b736f805463ffffffff19166302be14101781556127107fa32ac351050f01911d543184484dd0b56f1a44a545355195dea6fa48038b737055600a7fa32ac351050f01911d543184484dd0b56f1a44a545355195dea6fa48038b73715566038d7ea4c680007fa32ac351050f01911d543184484dd0b56f1a44a545355195dea6fa48038b73725560408051808201909152620138808152620186a060208201526101247fa32ac351050f01911d543184484dd0b56f1a44a545355195dea6fa48038b7373826002610129565b505050565b82805482825590600052602060002090600901600a900481019282156101c55791602002820160005b8382111561019457835183826101000a81548162ffffff021916908362ffffff1602179055509260200192600301602081600201049283019260010302610152565b80156101c35782816101000a81549062ffffff0219169055600301602081600201049283019260010302610194565b505b506101d19291506101d5565b5090565b5b808211156101d157600081556001016101d656fea2646970667358221220d1703a2e630f53d4bcff30348cabad8ef9f33be99677d6a68ea6c120ed97015964736f6c63430008120033";

type MagicPixelsInitConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MagicPixelsInitConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MagicPixelsInit__factory extends ContractFactory {
  constructor(...args: MagicPixelsInitConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MagicPixelsInit & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MagicPixelsInit__factory {
    return super.connect(runner) as MagicPixelsInit__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MagicPixelsInitInterface {
    return new Interface(_abi) as MagicPixelsInitInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MagicPixelsInit {
    return new Contract(address, _abi, runner) as unknown as MagicPixelsInit;
  }
}
