/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MagicPlatesInit,
  MagicPlatesInitInterface,
} from "../../../../contracts/diamond/upgradeInitializers/MagicPlatesInit";

const _abi = [
  {
    inputs: [],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061022f806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063e1c7392a14610030575b600080fd5b61003861003a565b005b61011b7fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c131f6020527f699d9daa71b280d05a152715774afa0a81a312594b2d731d6b0b2552b7d6f69f8054600160ff1991821681179092557ff97e938d8af42f52387bb74b8b526fda8f184cc2aa534340a8d75a88fbecc77580548216831790557f65d510a5d8f7ef134ec444f7f34ee808c8eeb5177cdfd16be0c40fe1ab43369580548216831790556307f5828d60e41b6000527f5622121b47b8cd0120c4efe45dd5483242f54a3d49bd7679be565d47694918c380549091169091179055565b7fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c131f6020527fb0f299ecb5b93181be17d5e233721498930c5361f367b1d41c5b827d4fe4d3808054600160ff1991821681179092557fc564b00dd622489e8872cfaa1fdbe51ee7adef071bfa99bc1effdc20162fa70a80548216831790557f325e4620d36cfbe0640b77d535666925c734295d4ff08b1c6f55cfa4a4e4d1dc805482168317905563152a902d60e11b6000527f0306b2e4a53af38a838ab3669d25ec0c1c034acfdbc7196c0eee0709be2858cc8054909116909117905556fea2646970667358221220ddc6ac16cd4773c2b16426c28f4a26c21f481a1b1e28a1b209fa91cd3854098a64736f6c63430008120033";

type MagicPlatesInitConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MagicPlatesInitConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MagicPlatesInit__factory extends ContractFactory {
  constructor(...args: MagicPlatesInitConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MagicPlatesInit & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MagicPlatesInit__factory {
    return super.connect(runner) as MagicPlatesInit__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MagicPlatesInitInterface {
    return new Interface(_abi) as MagicPlatesInitInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MagicPlatesInit {
    return new Contract(address, _abi, runner) as unknown as MagicPlatesInit;
  }
}
