/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as diamond from "./diamond";
export type { diamond };
export type { MagicPlates } from "./MagicPlates";
