/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auctionHouse from "./AuctionHouse";
export type { auctionHouse };
import type * as magicPixels from "./MagicPixels";
export type { magicPixels };
import type * as magicPlates from "./MagicPlates";
export type { magicPlates };
export type { DiamondCutFacet } from "./DiamondCutFacet";
export type { DiamondLoupeFacet } from "./DiamondLoupeFacet";
export type { OwnershipFacet } from "./OwnershipFacet";
export type { Test1Facet } from "./Test1Facet";
export type { Test2Facet } from "./Test2Facet";
