/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMagicPlates } from "./IMagicPlates";
export type { NFTFacet } from "./NFTFacet";
export type { PltsCore } from "./PltsCore";
