/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC2981Upgradeable__factory } from "./IERC2981Upgradeable__factory";
export { IERC4906Upgradeable__factory } from "./IERC4906Upgradeable__factory";
