/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMagicPixels } from "./IMagicPixels";
export type { PxlsCommon } from "./PxlsCommon";
export type { PxlsCore } from "./PxlsCore";
export type { PxlsSetters } from "./PxlsSetters";
